RENDER_HELPER = 0.01;

ROUNDING_RADIUS_BODY = 2;
ROUNDING_RADIUS_CUTOUT = 2;
ROUNDING_RADIUS_NOSE_NOTCH = 2;

FRAME_THICKNESS = 10;

NOSE_NOTCH_HEIGHT = 5;
NOSE_INSET_X = 7;
NOSE_INSET_Y = 3;
NOSE_NOTCH_SIZE_DIFF = 1;
